### ISSUE TITLE
Undefined method `ap' for Kernel:Module

### ISSUE THREAD

**Issue by stormmaster42** [thbar/kiba-common#40]
Trying to use `show_me!` in a simple example script.
I need to explicitly
`require "awesome_print"`.
Otherwise:
show_me.rb:11:in 'block in show_me!': undefined method 'ap' for Kernel:Module (NoMethodError)

(Ruby Version 3.1.2, kiba-common-1.5.0)

**Comment by thbar** [comment]
You are right! This is by design. The user is expected to manually require either `awesome_print` or `amazing_print`.

See this for the context:
- https://github.com/thbar/kiba-common/pull/32

Thanks for reporting this!

I'm fixing it in #41 by improving the documentation, which is not clear enough in that regard.

**Comment by thbar** [comment]
Fixed! Thank you!
